name: run_python

on:
  push:
    branches:
      - main
  #schedule:
  #  - cron: '0 3 * * *' # UTC 3:00

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: "3.8"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run main.py
        env:
            SLACK_TOKEN_PAPER_RESEARCH: ${{secrets.SLACK_TOKEN_PAPER_RESEARCH}}
        run: |
          python src/main.py $SLACK_TOKEN_PAPER_RESEARCH